(deftheme georgiboy-light
  "Created 2026-07-10.")

(custom-theme-set-faces
 'georgiboy-light
 '(cursor ((t (:background "#d00000"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#a60000"))))
 '(homoglyph ((t (:foreground "#884900"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:foreground "#000000" :background "#b2e4dc"))))
 '(region ((t (:extend t :foreground "#000000" :background "#c2bcb5"))))
 '(shadow ((t (:background "gray94" :foreground "#595959"))))
 '(secondary-selection ((t (:extend t :foreground "#000000" :background "#f5d0a0"))))
 '(trailing-whitespace ((t (:background "#ff8f88"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#8f0075" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#7f0000" :inherit (modus-themes-slant)))))
 '(font-lock-constant-face ((t (:foreground "#0000b0"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#2a5045" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#7c318f" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#721045"))))
 '(font-lock-keyword-face ((t (:inherit modus-themes-bold :background "thistle1" :foreground "#531ab6"))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-operator-face ((t (:inherit font-lock-punctuation-fyyace))))
 '(font-lock-preprocessor-face ((t (:foreground "#a0132f"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "LavenderBlush4" :weight semi-light))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#721045" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00663f" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#721045" :weight normal))))
 '(font-lock-type-face ((t (:inherit modus-themes-bold :background "ivory2" :foreground "#005f5f" :slant italic))))
 '(font-lock-variable-name-face ((t (:background "azure2" :foreground "#005e8b" :weight semi-bold))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#884900" :inherit (modus-themes-bold)))))
 '(button ((t (:underline (:color "#3548cf" :style line :position nil) :foreground "#3548cf"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:underline (:color "#721045" :style line :position nil) :foreground "#721045"))))
 '(fringe ((t (:foreground "#000000" :background "#efe9dd"))))
 '(header-line ((t (:background "#efe9dd" :inherit (modus-themes-ui-variable-pitch)))))
 '(tooltip ((t (:foreground "#000000" :background "#c9b9b0"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#545454" :style nil) :foreground "#000000" :background "#cab9b2" :inherit (modus-themes-ui-variable-pitch)))))
 '(mode-line-buffer-id ((t (:inherit bold :weight semi-bold))))
 '(mode-line-emphasis ((t (:foreground "#002580" :inherit (bold)))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#000000" :style nil) :foreground "#000000" :background "#b2e4dc"))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#a59a94" :style nil) :foreground "#585858" :background "#dfd9cf" :inherit (modus-themes-ui-variable-pitch)))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#000000" :background "#ffddff"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace)))))
 '(default ((t (:family "IBM Plex Mono" :foundry "IBM " :width normal :height 166 :weight medium :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#000000" :background "#fbf7f0" :stipple nil :inherit nil)))))

(provide-theme 'georgiboy-light)
